name: Build and Push Docker Image

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout CI repo
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        run: |
          docker build -t swaroops2803/gitops-eks-app:${{ github.run_number }} .
          docker push swaroops2803/gitops-eks-app:${{ github.run_number }}

      - name: Clone GitOps CD repo
        run: |
          git clone https://keshavswaroop:${{ secrets.REPO_GITHUB_TOKEN }}@github.com/keshavswaroop/gitops-eks-cd.git

      - name: Update deployment image
        run: |
          sed -i "s|image: .*|image: swaroops2803/gitops-eks-app:${{ github.run_number }}|" \
          gitops-eks-cd/apps/app/deployment.yml

      - name: Commit and push changes
        run: |
          cd gitops-eks-cd
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add apps/app/deployment.yml
          git commit -m "Update image to ${{ github.run_number }}"
          git push
